use geom;
DECLARE @h geography;  
SET @h = geography::STGeomFromText('POLYGON((0 0, 2 0, 0 2, 0 0))',4326).MakeValid();  
SET STATISTICS TIME ON;
SELECT count(*) from poly7 where geom.STContains(@h)=1;
SELECT count(*) from poly7 where geom.STContains(@h)=1;
SET STATISTICS TIME off;
SET STATISTICS TIME ON;
SELECT count(*) from poly8 where geom.STContains(@h)=1;
SET STATISTICS TIME off;
SET STATISTICS TIME ON;
SELECT count(*) from poly9 where geom.STContains(@h)=1;
SET STATISTICS TIME off;
SET STATISTICS TIME ON;
SELECT count(*) from poly10 where geom.STContains(@h)=1;
SET STATISTICS TIME off;
SET STATISTICS TIME ON;
SELECT count(*) from poly11 where geom.STContains(@h)=1;
SET STATISTICS TIME off;
