USE [geom]
ALTER TABLE [dbo].[poly20] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly40] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly60] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly80] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly100] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly120] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly140] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly160] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)
ALTER TABLE [dbo].[poly180] REBUILD PARTITION = ALL
WITH
(DATA_COMPRESSION = PAGE
)

